apiVersion: v1
kind: Service
metadata:
  name: data-consumer-graalvm
spec:
  type: ClusterIP
  ports:
  - name: prometheus
    port: 9999
  - name: grpc
    port: 50051
  selector:
    app: data-consumer-graalvm

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: data-consumer-graalvm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-consumer-graalvm
  template:
    metadata:
      labels:
        app: data-consumer-graalvm
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hardened
                operator: NotIn
                values:
                - "true"
      securityContext:
        runAsUser: 65534
      containers:
      - name: data-consumer-graalvm
        image: "wharf.gaikai.org/lbachmann/hackathon-data-consumer-alpine-graalvm:0.0.1"
        command: ["java"]
        args: ["-jar", "-Xmx1024m", "/tmp/data-consumer.jar"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9999
        - containerPort: 50051
        resources:
          limits:
            cpu: 2
            memory: 1Gi
      restartPolicy: Always