apiVersion: v1
kind: Service
metadata:
  name: data-consumer-jvm-objectify
spec:
  type: ClusterIP
  ports:
  - name: prometheus
    port: 9999
  - name: grpc
    port: 50051
  selector:
    app: data-consumer-jvm-objectify

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: data-consumer-jvm-objectify
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-consumer-jvm-objectify
  template:
    metadata:
      labels:
        app: data-consumer-jvm-objectify
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hardened
                operator: NotIn
                values:
                - "true"
      securityContext:
        runAsUser: 65534
      containers:
      - name: data-consumer-jvm-objectify
        image: "wharf.gaikai.org/lbachmann/hackathon-data-consumer-alpine-jvm:0.0.1"
        command: ["java"]
        args: ["-jar", "-Xmx1024m", "/tmp/data-consumer.jar", "1"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9999
        - containerPort: 50051
        resources:
          limits:
            cpu: 2
            memory: 1Gi
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: data-consumer-jvm-streaming
spec:
  type: ClusterIP
  ports:
  - name: prometheus
    port: 9999
  - name: grpc
    port: 50051
  selector:
    app: data-consumer-jvm-streaming

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: data-consumer-jvm-streaming
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-consumer-jvm-streaming
  template:
    metadata:
      labels:
        app: data-consumer-jvm-streaming
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hardened
                operator: NotIn
                values:
                - "true"
      securityContext:
        runAsUser: 65534
      containers:
      - name: data-consumer-jvm-streaming
        image: "wharf.gaikai.org/lbachmann/hackathon-data-consumer-alpine-jvm:0.0.1"
        command: ["java"]
        args: ["-jar", "-Xmx1024m", "/tmp/data-consumer.jar", "2"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9999
        - containerPort: 50051
        resources:
          limits:
            cpu: 2
            memory: 1Gi
      restartPolicy: Always

---

apiVersion: v1
kind: Service
metadata:
  name: data-consumer-jvm-decryption
spec:
  type: ClusterIP
  ports:
  - name: prometheus
    port: 9999
  - name: grpc
    port: 50051
  selector:
    app: data-consumer-jvm-decryption

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: data-consumer-jvm-decryption
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-consumer-jvm-decryption
  template:
    metadata:
      labels:
        app: data-consumer-jvm-decryption
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hardened
                operator: NotIn
                values:
                - "true"
      securityContext:
        runAsUser: 65534
      containers:
      - name: data-consumer-jvm-decryption
        image: "wharf.gaikai.org/lbachmann/hackathon-data-consumer-alpine-jvm:0.0.1"
        command: ["java"]
        args: ["-jar", "-Xmx1024m", "/tmp/data-consumer.jar", "3"]
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9999
        - containerPort: 50051
        resources:
          limits:
            cpu: 2
            memory: 1Gi
      restartPolicy: Always
