apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: data-producer
spec:
  replicas: 10
  selector:
    matchLabels:
      app: data-producer
  template:
    metadata:
      labels:
        app: data-producer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hardened
                operator: NotIn
                values:
                - "true"
      containers:
      - name: data-producer
        image: "wharf.gaikai.org/lbachmann/hackathon-data-producer-gentoo-jvm:0.0.1"
        command: ["java"]
        args: ["-jar", "-Xmx512m", "/tmp/data-producer.jar", "data-consumer-jvm-streaming", "data-consumer-jvm-decryption", "data-consumer-jvm-objectify", "data-consumer-graalvm-streaming", "data-consumer-graalvm-decryption", "data-consumer-graalvm-objectify"]
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 1
            memory: 512Mi
      restartPolicy: Always