apiVersion: v1
data:
  prometheus-datasource.yml: |
    {"id":1,"orgId":1,"name":"prometheus","type":"prometheus","typeLogoUrl":"public/app/plugins/datasource/prometheus/img/prometheus_logo.svg","access":"proxy","url":"http://prometheus:9090","password":"","user":"","database":"","basicAuth":false,"isDefault":true,"jsonData":{"httpMethod":"GET","keepCookies":[]},"readOnly":false}
  graalvm-evaluation-dashboard.yml: |
    {
      "dashboard": {
        "__inputs": [
          {
            "name": "DS_PROMETHEUS",
            "label": "prometheus",
            "description": "",
            "type": "datasource",
            "pluginId": "prometheus",
            "pluginName": "Prometheus"
          }
        ],
        "__requires": [
          {
            "type": "grafana",
            "id": "grafana",
            "name": "Grafana",
            "version": "6.2.5"
          },
          {
            "type": "panel",
            "id": "graph",
            "name": "Graph",
            "version": ""
          },
          {
            "type": "datasource",
            "id": "prometheus",
            "name": "Prometheus",
            "version": "1.0.0"
          }
        ],
        "annotations": {
          "list": [
            {
              "builtIn": 1,
              "datasource": "-- Grafana --",
              "enable": true,
              "hide": true,
              "iconColor": "rgba(0, 211, 255, 1)",
              "name": "Annotations & Alerts",
              "type": "dashboard"
            }
          ]
        },
        "editable": true,
        "gnetId": null,
        "graphTooltip": 0,
        "id": null,
        "links": [],
        "panels": [
          {
            "aliasColors": {},
            "bars": false,
            "dashLength": 10,
            "dashes": false,
            "datasource": "prometheus",
            "fill": 1,
            "gridPos": {
              "h": 9,
              "w": 12,
              "x": 0,
              "y": 0
            },
            "id": 2,
            "legend": {
              "avg": false,
              "current": false,
              "max": false,
              "min": false,
              "show": true,
              "total": false,
              "values": false
            },
            "lines": true,
            "linewidth": 1,
            "links": [],
            "nullPointMode": "null",
            "options": {},
            "percentage": false,
            "pointradius": 2,
            "points": false,
            "renderer": "flot",
            "seriesOverrides": [],
            "spaceLength": 10,
            "stack": false,
            "steppedLine": false,
            "targets": [
              {
                "expr": "grpc_requests_total",
                "format": "time_series",
                "intervalFactor": 1,
                "legendFormat": "{{pod}}",
                "refId": "A"
              }
            ],
            "thresholds": [],
            "timeFrom": null,
            "timeRegions": [],
            "timeShift": null,
            "title": "GRPC requests",
            "tooltip": {
              "shared": true,
              "sort": 0,
              "value_type": "individual"
            },
            "type": "graph",
            "xaxis": {
              "buckets": null,
              "mode": "time",
              "name": null,
              "show": true,
              "values": []
            },
            "yaxes": [
              {
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
              },
              {
                "format": "short",
                "label": null,
                "logBase": 1,
                "max": null,
                "min": null,
                "show": true
              }
            ],
            "yaxis": {
              "align": false,
              "alignLevel": null
            }
          }
        ],
        "schemaVersion": 18,
        "style": "dark",
        "tags": [],
        "templating": {
          "list": []
        },
        "time": {
          "from": "now-5m",
          "to": "now"
        },
        "timepicker": {
          "refresh_intervals": [
            "5s",
            "10s",
            "30s",
            "1m",
            "5m",
            "15m",
            "30m",
            "1h",
            "2h",
            "1d"
          ],
          "time_options": [
            "5m",
            "15m",
            "1h",
            "6h",
            "12h",
            "24h",
            "2d",
            "7d",
            "30d"
          ]
        },
        "timezone": "",
        "title": "GraalVM",
        "uid": "9cR2EmHZz",
        "version": 1
      }
    }
kind: ConfigMap
metadata:
  name: grafana-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  type: LoadBalancer
  ports:
  - name: grafana
    port: 3000
    nodePort: 30080
  selector:
    app: grafana

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 472
      containers:
      - name: grafana
        image: wharf.gaikai.org/lbachmann/grafana:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: GF_SERVER_ROOT_URL
          value: http://grafana
        - name: GF_SECURITY_ADMIN_PASSWORD
          value: secret
        ports:
        - containerPort: 3000
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hardened
                operator: In
                values:
                - "false"

---

apiVersion: batch/v1
kind: Job
metadata:
  name: grafana-init-job
spec:
  template:
    spec:
      securityContext:
        runAsNonRoot: false
      containers:
      - name: grafana-init-job
        image: wharf.gaikai.org/lbachmann/curl:alpine
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: grafana-config
          mountPath: /opt/grafana
        command: ["/bin/sh"]
        args: ["-c", "sleep 20 && curl -X 'POST' 'http://grafana:3000/api/datasources' -H 'Content-Type: application/json' --user admin:secret --data-binary @/opt/grafana/prometheus-datasource.yml && curl -X 'POST' 'http://grafana:3000/api/dashboards/db' -H 'Content-Type: application/json' --user admin:secret --data-binary @/opt/grafana/graalvm-evaluation-dashboard.yml"]
        #args: ["-c", "sleep 1000000000"]
      restartPolicy: Never
      volumes:
      - name: grafana-config
        configMap:
          name: grafana-configmap
          items:
          - key: prometheus-datasource.yml
            path: prometheus-datasource.yml
          - key: graalvm-evaluation-dashboard.yml
            path: graalvm-evaluation-dashboard.yml
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hardened
                operator: In
                values:
                - "false"
  backoffLimit: 0