apiVersion: v1
data:
  prometheus.yml: |
    # my global config
    global:
      scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
      evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
      # scrape_timeout is set to the global default (10s).

    # Alertmanager configuration
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          # - alertmanager:9093

    rule_files:
    scrape_configs:
      - job_name: 'data-consumer-graalvm-objectify'
        static_configs:
        - targets: ['data-consumer-graalvm-objectify.graal.svc.cluster.local:9999']
      - job_name: 'data-consumer-graalvm-streaming'
        static_configs:
        - targets: ['data-consumer-graalvm-streaming.graal.svc.cluster.local:9999']
      - job_name: 'data-consumer-graalvm-decryption'
        static_configs:
        - targets: ['data-consumer-graalvm-decryption.graal.svc.cluster.local:9999']
      - job_name: 'data-consumer-jvm-objectify'
        static_configs:
        - targets: ['data-consumer-jvm-objectify.graal.svc.cluster.local:9999']
      - job_name: 'data-consumer-jvm-streaming'
        static_configs:
        - targets: ['data-consumer-jvm-streaming.graal.svc.cluster.local:9999']
      - job_name: 'data-consumer-jvm-decryption'
        static_configs:
        - targets: ['data-consumer-jvm-decryption.graal.svc.cluster.local:9999']
kind: ConfigMap
metadata:
  name: prometheus-configmap

---

apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  type: NodePort
  ports:
  - name: prometheus
    port: 9090
    nodePort: 30082
  selector:
    app: prometheus

---

apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      securityContext:
        runAsUser: 65534
      containers:
      - name: prometheus
        image: wharf.gaikai.org/lbachmann/prometheus:master
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-configmap
          items:
          - key: prometheus.yml
            path: prometheus.yml
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: hardened
                operator: In
                values:
                - "false"